CREATE TABLE `qq` (
	`uin` BIGINT(20) UNSIGNED NOT NULL,
	`nick` VARCHAR(64) NULL DEFAULT NULL,
	`parent` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
	`ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`uin`),
	INDEX `parent` (`parent`)
)
ENGINE=InnoDB;
